version: '3.7'

services:
  micro-api:
    container_name: micro-api
    build:
      dockerfile: Dockerfile
      context: ./micro-api
    ports:
      - 9000:9000
    volumes:
      - ./micro-api:/var/www
  nginx_micro:
    container_name: nginx_micro
    image: nginx
    ports:
      - 8081:80
    volumes:
      - ./micro-api:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - micro-api
  # MYSQL
  database:
    container_name: mysql_db
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: rootuser
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql/:/var/lib/mysql/